import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro",
   "metadata": {},
   "source": [
    "# Reservoir Neuron Dynamics & Pruning/Genesis Visualization (Initial 500 Steps)\n",
    "\n",
    "This notebook runs the reservoir on the Tiny Shakespeare dataset, tracking and plotting neuron dynamics (states, slow/fast trails, and homeostatic scaling factor), as well as pruning, genesis, and recurrent weight density (non-zero connections) for the first 500 steps."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import torch\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Ensure model module is importable\n",
    "sys.path.append(os.path.abspath('.'))\n",
    "sys.path.append(os.path.abspath('..'))\n",
    "\n",
    "from model.reservoir import Reservoir"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "load_data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Load Shakespeare dataset\n",
    "dataset_path = os.path.join(\"dataset\", \"tinyshakespeare.txt\")\n",
    "if not os.path.exists(dataset_path):\n",
    "    dataset_path = os.path.join(\"..\", \"dataset\", \"tinyshakespeare.txt\")\n",
    "\n",
    "with open(dataset_path, \"r\", encoding=\"utf-8\") as f:\n",
    "    text = f.read()\n",
    "\n",
    "print(f\"Dataset loaded. Length: {len(text)} characters.\")\n",
    "vocab = sorted(list(set(text)))\n",
    "vocab_size = len(vocab)\n",
    "char2idx = {char: idx for idx, char in enumerate(vocab)}\n",
    "idx2char = {idx: char for idx, char in enumerate(vocab)}\n",
    "print(f\"Vocab size: {vocab_size}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "simulation_run",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Initialize reservoir and run simulation for 500 steps from step 0\n",
    "res_size = 500\n",
    "input_scaling = 1.0\n",
    "reservoir = Reservoir(res_size, vocab_size, input_scaling=input_scaling, density=0.01)\n",
    "\n",
    "train_len = 500\n",
    "states_first_500 = []\n",
    "slow_trail_first_500 = []\n",
    "fast_trail_first_500 = []\n",
    "scaling_first_500 = []\n",
    "\n",
    "genesis_ops = []\n",
    "pruning_ops = []\n",
    "non_zero_connections = []\n",
    "\n",
    "reservoir.reset_state()\n",
    "print(\"Stepping through the text...\")\n",
    "for i in range(train_len):\n",
    "    char_idx = char2idx[text[i]]\n",
    "    x_onehot = torch.zeros(vocab_size)\n",
    "    x_onehot[char_idx] = 1.0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        reservoir.step(x_onehot)\n",
    "        \n",
    "    # Record dynamics\n",
    "    states_first_500.append(reservoir.state.clone().numpy())\n",
    "    slow_trail_first_500.append(reservoir.slow_trail.clone().numpy())\n",
    "    fast_trail_first_500.append(reservoir.fast_trail.clone().numpy())\n",
    "    scaling_first_500.append(reservoir.scaling.clone().numpy())\n",
    "        \n",
    "    # Record operations and connection counts\n",
    "    genesis_ops.append(reservoir.latest_genesis_ops)\n",
    "    pruning_ops.append(reservoir.latest_pruning_ops)\n",
    "    non_zero_connections.append(torch.count_nonzero(reservoir.W).item())\n",
    "\n",
    "states_first_500 = np.stack(states_first_500)\n",
    "slow_trail_first_500 = np.stack(slow_trail_first_500)\n",
    "fast_trail_first_500 = np.stack(fast_trail_first_500)\n",
    "scaling_first_500 = np.stack(scaling_first_500)\n",
    "\n",
    "genesis_ops = np.array(genesis_ops)\n",
    "pruning_ops = np.array(pruning_ops)\n",
    "non_zero_connections = np.array(non_zero_connections)\n",
    "print(\"Finished stepping.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "plot_dynamics",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Plot initial dynamics (first 500 steps)\n",
    "neurons_to_plot = [0, 1, 2, 3, 4]\n",
    "fig, axes = plt.subplots(4, 1, figsize=(12, 12), sharex=True)\n",
    "\n",
    "# States\n",
    "for n in neurons_to_plot:\n",
    "    axes[0].plot(states_first_500[:, n], label=f\"Neuron {n}\", alpha=0.8)\n",
    "axes[0].set_ylabel(\"State value\")\n",
    "axes[0].set_title(\"Neuron States (Initial 500 Steps)\")\n",
    "axes[0].legend(loc=\"upper right\")\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Slow Trail\n",
    "for n in neurons_to_plot:\n",
    "    axes[1].plot(slow_trail_first_500[:, n], alpha=0.8)\n",
    "axes[1].axhline(0.1, color=\"red\", linestyle=\"--\", alpha=0.5, label=\"Low Limit (0.1)\")\n",
    "axes[1].axhline(0.9, color=\"blue\", linestyle=\"--\", alpha=0.5, label=\"High Limit (0.9)\")\n",
    "axes[1].set_ylabel(\"Slow Trail\")\n",
    "axes[1].set_title(\"Slow Trail (Used by Homeostasis)\")\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "# Fast Trail\n",
    "for n in neurons_to_plot:\n",
    "    axes[2].plot(fast_trail_first_500[:, n], alpha=0.8)\n",
    "axes[2].set_ylabel(\"Fast Trail\")\n",
    "axes[2].set_title(\"Fast Trail (Short-term memory)\")\n",
    "axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "# Scaling\n",
    "for n in neurons_to_plot:\n",
    "    axes[3].plot(scaling_first_500[:, n], alpha=0.8)\n",
    "axes[3].set_ylabel(\"Scaling factor\")\n",
    "axes[3].set_xlabel(\"Time steps\")\n",
    "axes[3].set_title(\"Homeostatic Scaling Weights (Gain Control)\")\n",
    "axes[3].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "plot_ops",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Plot the pruning, genesis, and active connection count over time (first 500 steps)\n",
    "fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 14))\n",
    "\n",
    "# Plot cumulative operations\n",
    "ax1.plot(np.cumsum(genesis_ops), label=\"Cumulative Genesis (Additions)\", color=\"green\", linewidth=2)\n",
    "ax1.plot(np.cumsum(pruning_ops), label=\"Cumulative Pruning (Weakenings)\", color=\"red\", linewidth=2)\n",
    "ax1.set_ylabel(\"Cumulative Count\")\n",
    "ax1.set_title(\"Cumulative Pruning and Genesis Operations Over Time (First 500 Steps)\")\n",
    "ax1.legend()\n",
    "ax1.grid(True, alpha=0.3)\n",
    "\n",
    "# Plot moving average of operations (to see stability/density)\n",
    "window_size = 50\n",
    "def moving_average(a, n=window_size):\n",
    "    ret = np.cumsum(a, dtype=float)\n",
    "    ret[n:] = ret[n:] - ret[:-n]\n",
    "    return ret[n - 1:] / n\n",
    "\n",
    "ma_genesis = moving_average(genesis_ops)\n",
    "ma_pruning = moving_average(pruning_ops)\n",
    "steps_ma = np.arange(window_size - 1, train_len)\n",
    "\n",
    "ax2.plot(steps_ma, ma_genesis, label=f\"Genesis (MA {window_size} steps)\", color=\"green\", alpha=0.7)\n",
    "ax2.plot(steps_ma, ma_pruning, label=f\"Pruning (MA {window_size} steps)\", color=\"red\", alpha=0.7)\n",
    "ax2.set_ylabel(\"Average Operations per Step\")\n",
    "ax2.set_title(\"Rate of Pruning and Genesis Operations\")\n",
    "ax2.legend()\n",
    "ax2.grid(True, alpha=0.3)\n",
    "\n",
    "# Plot active connections count in W\n",
    "ax3.plot(non_zero_connections, label=\"Active Recurrent Connections (W != 0)\", color=\"purple\", linewidth=2)\n",
    "ax3.set_xlabel(\"Time steps\")\n",
    "ax3.set_ylabel(\"Number of Connections\")\n",
    "ax3.set_title(\"Recurrent Weight Matrix Density Dynamics (Non-zero Connections in W)\")\n",
    "ax3.legend()\n",
    "ax3.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("tesi/prune_genesis.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook generated successfully!")
